name: Build Action

description: "Build and test project"

runs:
  using: "composite"
  steps:
    - name: Build
      run: mvn clean install
      shell: bash

    - name: Test
      run: mvn test
      shell: bash

    - name: Done
      run: echo "Build Completed"
      shell: bash
