name: 16 - Java CI(Composite)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: java/JavaCicd 

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Java Composite Action
        uses: ./.github/actions/composite-cache-dependncies
